import React, { useEffect } from "react";
import Head from "next/head";
import {
  Box,
  Typography,
  Paper,
  TextField,
  Button,
  Grid,
  Divider,
} from "@mui/material";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <Box>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography variant="h3" align="center">
        Register Account:
      </Typography>
      <Box>
        <Paper
          variant="outlined"
          sx={{
            margin: "auto",
            width: 750,
          }}
        >
          <Typography
            sx={{
              backgroundColor: "#241f1f80",
              color: "white",
              fontWeight: "bold",
              textAlign: "center",
              padding: 1.2,
              marginBottom: 3,
            }}
          >
            Personal Information
          </Typography>
          <Grid
            container
            spacing={1}
            sx={{
              padding: 2,
            }}
          >
            <Grid item>
              <TextField size="small" placeholder="Name" />
            </Grid>
            <Grid item>
              <TextField size="small" placeholder="Username" />
            </Grid>
            <Grid item>
              <TextField size="small" placeholder="Email" />
            </Grid>
          </Grid>
          <Divider
            sx={{
              marginTop: 3,
            }}
          />

          <Typography
            sx={{
              backgroundColor: "#241f1f80",
              color: "white",
              fontWeight: "bold",
              textAlign: "center",
              padding: 1.2,
              marginBottom: 3,
            }}
          >
            Contact Information
          </Typography>
          <Grid
            container
            spacing={1}
            sx={{
              padding: 2,
            }}
          >
            <Grid item xs={4}>
              <TextField size="small" placeholder="Street" />
            </Grid>
            <Grid item xs={4}>
              <TextField size="small" placeholder="House number" />
            </Grid>
            <Grid item xs={4}>
              <TextField size="small" placeholder="City" />
            </Grid>
            <Grid item container>
              <Grid item xs={4}>
                <TextField size="small" placeholder="Zip code" />
              </Grid>
              <Grid item xs={4}>
                <TextField size="small" placeholder="Contact No." />
              </Grid>
              <Grid item xs={4}>
                <TextField size="small" placeholder="Website" />
              </Grid>
            </Grid>
          </Grid>
          <Divider
            sx={{
              marginTop: 3,
            }}
          />

          <Typography
            sx={{
              backgroundColor: "#241f1f80",
              color: "white",
              fontWeight: "bold",
              textAlign: "center",
              padding: 1.2,
              marginBottom: 3,
            }}
          >
            Company Information
          </Typography>
          <Grid
            container
            spacing={1}
            sx={{
              padding: 2,
            }}
          >
            <Grid item xs={4}>
              <TextField size="small" placeholder="Name" />
            </Grid>
            <Grid item xs={4}>
              <TextField size="small" placeholder="Catchphrase" />
            </Grid>
            <Grid item xs={4}>
              <TextField size="small" placeholder="BS" />
            </Grid>
          </Grid>

          <Box
            display="flex"
            textAlign="right"
            gap="10px"
            justifyContent="flex-end"
            sx={{
              marginBottom: 1,
              marginRight: 1,
            }}
          >
            <Button
              disableElevation
              variant="contained"
              sx={{
                textTransform: "none",
              }}
              color="error"
            >
              Clear form
            </Button>
            <Button
              disableElevation
              variant="contained"
              sx={{
                textTransform: "none",
              }}
            >
              Submit
            </Button>
          </Box>
        </Paper>
      </Box>
    </Box>
  );
}
